// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetUserResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserResponse) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type PostUserResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostUserResponse) Reset()         { *m = PostUserResponse{} }
func (m *PostUserResponse) String() string { return proto.CompactTextString(m) }
func (*PostUserResponse) ProtoMessage()    {}
func (*PostUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}
func (m *PostUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUserResponse.Unmarshal(m, b)
}
func (m *PostUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUserResponse.Marshal(b, m, deterministic)
}
func (m *PostUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUserResponse.Merge(m, src)
}
func (m *PostUserResponse) XXX_Size() int {
	return xxx_messageInfo_PostUserResponse.Size(m)
}
func (m *PostUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostUserResponse proto.InternalMessageInfo

func (m *PostUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostUserResponse) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type GetUserRequest struct {
	my_name              string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" gorm:"column:name"`
	Age                  int64      `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	CreateDate           *time.Time `protobuf:"bytes,3,opt,name=create_date,json=createDate,proto3,stdtime" json:"create_date,omitempty"`
	Id                   string     `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) Getmy_name() string {
	if m != nil {
		return m.my_name
	}
	return ""
}

func (m *GetUserRequest) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *GetUserRequest) GetCreateDate() *time.Time {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PostUserRequest struct {
	my_name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" gorm:"column:name"`
	Age                  int64                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	CreateDate           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	Id                   string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PostUserRequest) Reset()         { *m = PostUserRequest{} }
func (m *PostUserRequest) String() string { return proto.CompactTextString(m) }
func (*PostUserRequest) ProtoMessage()    {}
func (*PostUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}
func (m *PostUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUserRequest.Unmarshal(m, b)
}
func (m *PostUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUserRequest.Marshal(b, m, deterministic)
}
func (m *PostUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUserRequest.Merge(m, src)
}
func (m *PostUserRequest) XXX_Size() int {
	return xxx_messageInfo_PostUserRequest.Size(m)
}
func (m *PostUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostUserRequest proto.InternalMessageInfo

func (m *PostUserRequest) Getmy_name() string {
	if m != nil {
		return m.my_name
	}
	return ""
}

func (m *PostUserRequest) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PostUserRequest) GetCreateDate() *timestamppb.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *PostUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserResponse)(nil), "GetUserResponse")
	proto.RegisterType((*PostUserResponse)(nil), "PostUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "GetUserRequest")
	proto.RegisterType((*PostUserRequest)(nil), "PostUserRequest")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xcf, 0x6f, 0xd3, 0x4a,
	0x10, 0xee, 0x3a, 0xee, 0x4b, 0xba, 0x79, 0x7d, 0x49, 0xb7, 0xd2, 0x53, 0x64, 0xf5, 0xc9, 0x7e,
	0xa6, 0x42, 0x55, 0xa4, 0xda, 0x69, 0x10, 0x01, 0xe5, 0x54, 0x47, 0xad, 0x2a, 0xe0, 0x40, 0x15,
	0x95, 0x4b, 0x2f, 0xd5, 0xc6, 0x99, 0x9a, 0x2d, 0xf1, 0xee, 0xd6, 0xbb, 0x4e, 0x81, 0x23, 0x7f,
	0x41, 0x15, 0x6e, 0x9c, 0xf9, 0x63, 0x38, 0xc3, 0xbd, 0x95, 0x2a, 0x8e, 0x9c, 0x10, 0x12, 0x57,
	0x64, 0xc7, 0xa5, 0xbf, 0x2e, 0xfc, 0x38, 0x70, 0xda, 0xd9, 0x99, 0xf9, 0xf6, 0x9b, 0x99, 0x6f,
	0x16, 0xcf, 0xc3, 0x73, 0x1a, 0xcb, 0x11, 0x78, 0x32, 0x11, 0x5a, 0x58, 0x56, 0x7e, 0xf8, 0x91,
	0x88, 0xc4, 0x85, 0x55, 0xc4, 0xec, 0x48, 0x88, 0x68, 0x04, 0x7e, 0x7e, 0x1b, 0xa4, 0xfb, 0xbe,
	0x66, 0x31, 0x28, 0x4d, 0x63, 0x59, 0x24, 0xfc, 0x37, 0x85, 0xc4, 0x47, 0x4c, 0x3f, 0x13, 0x47,
	0xfe, 0x98, 0x8e, 0xd8, 0x90, 0x6a, 0x91, 0x14, 0xe1, 0xa5, 0x02, 0x4f, 0x25, 0xf3, 0x29, 0xe7,
	0x42, 0x53, 0xcd, 0x04, 0x57, 0x45, 0x74, 0x7a, 0x84, 0xab, 0x11, 0xf0, 0x55, 0x21, 0x81, 0x53,
	0xc9, 0xc6, 0x6d, 0x5f, 0xc8, 0x3c, 0xe7, 0x66, 0xbe, 0x7b, 0x0f, 0xd7, 0xb6, 0x40, 0x3f, 0x51,
	0x90, 0xf4, 0x41, 0x49, 0xc1, 0x15, 0x10, 0x82, 0x4d, 0x4e, 0x63, 0x68, 0x20, 0x07, 0xad, 0xcc,
	0xf5, 0x73, 0x9b, 0xd4, 0x71, 0x89, 0x46, 0xd0, 0x30, 0x1c, 0xb4, 0x52, 0xea, 0x67, 0xa6, 0x7b,
	0x1f, 0xd7, 0xb7, 0x85, 0xfa, 0x15, 0xe4, 0x57, 0x84, 0xff, 0xf9, 0xce, 0x79, 0x98, 0x82, 0xd2,
	0xe4, 0xee, 0x65, 0x60, 0xef, 0xff, 0xb3, 0x13, 0xbb, 0x1c, 0xbf, 0xd8, 0xcb, 0x5c, 0x9f, 0x4f,
	0x6c, 0x12, 0x89, 0x24, 0xee, 0xba, 0xa1, 0x18, 0xa5, 0x31, 0xef, 0x66, 0x4e, 0xb7, 0x78, 0xbb,
	0x73, 0xe9, 0xed, 0xde, 0xf2, 0xd9, 0xa9, 0xed, 0xd4, 0x67, 0x9a, 0x4b, 0x34, 0x02, 0x27, 0x4e,
	0x95, 0x76, 0x06, 0xe0, 0x48, 0xa1, 0x98, 0x66, 0x63, 0x70, 0x18, 0xd7, 0x10, 0x41, 0x92, 0x57,
	0x40, 0x36, 0x71, 0x35, 0x4c, 0x80, 0x6a, 0xd8, 0x1b, 0x52, 0x0d, 0x8d, 0x92, 0x83, 0x56, 0xaa,
	0x6d, 0xcb, 0x9b, 0x0e, 0xd6, 0x3b, 0x17, 0xc6, 0xdb, 0x39, 0x17, 0xa6, 0x57, 0x79, 0x77, 0x62,
	0xa3, 0xe3, 0x53, 0x1b, 0xf5, 0xf1, 0x14, 0xb8, 0x41, 0x35, 0x90, 0x5b, 0xd8, 0x60, 0xc3, 0x86,
	0x99, 0xd7, 0xbc, 0x78, 0x76, 0x6a, 0xd7, 0x9a, 0x98, 0xf1, 0x5c, 0x2e, 0x87, 0x0d, 0x8f, 0x91,
	0xd9, 0x37, 0xd8, 0xb0, 0x8b, 0x27, 0x41, 0x19, 0xcf, 0xbe, 0x47, 0x06, 0x1b, 0xba, 0x5f, 0x10,
	0xae, 0x5d, 0x0c, 0xed, 0x8f, 0xb4, 0x1e, 0xfc, 0x6c, 0xeb, 0x66, 0xd6, 0xfa, 0x6f, 0xb5, 0xdd,
	0xfe, 0x84, 0x70, 0x29, 0x90, 0x8c, 0x70, 0x5c, 0x2e, 0x74, 0x27, 0x35, 0xef, 0xea, 0x06, 0x58,
	0x75, 0xef, 0xda, 0x1a, 0xba, 0xeb, 0x93, 0xa0, 0x85, 0xcd, 0x3c, 0xbb, 0xb2, 0x05, 0xda, 0xc9,
	0xac, 0x87, 0x55, 0x5c, 0x6a, 0xb7, 0x5a, 0xc4, 0xc4, 0xc6, 0xe3, 0x47, 0x83, 0x05, 0x5c, 0xc3,
	0xd5, 0x10, 0x12, 0xcd, 0xf6, 0x59, 0x98, 0x55, 0x36, 0xf3, 0xea, 0xc3, 0xc7, 0xd7, 0x46, 0x99,
	0xcc, 0xfa, 0x69, 0x06, 0x4b, 0x71, 0xe5, 0x7c, 0xda, 0xa4, 0xee, 0x5d, 0x1b, 0xbc, 0xb5, 0xe0,
	0x5d, 0xdf, 0x5f, 0x77, 0x63, 0x12, 0xac, 0x15, 0x94, 0x73, 0x59, 0xf0, 0xc7, 0x39, 0xb1, 0x3b,
	0xe5, 0xec, 0xa2, 0x66, 0xef, 0x2d, 0x9a, 0x04, 0x6f, 0x10, 0xd9, 0xc4, 0x95, 0x1d, 0x50, 0xda,
	0x09, 0xb6, 0x1f, 0x90, 0xbf, 0x73, 0x6b, 0x0c, 0x89, 0x62, 0x82, 0xbb, 0xb7, 0xf1, 0xf4, 0x2e,
	0x13, 0x71, 0x00, 0xa1, 0xb6, 0xfe, 0xa5, 0x87, 0x34, 0x4d, 0x58, 0xaa, 0x3a, 0x9d, 0x4e, 0x67,
	0x3d, 0x8a, 0x29, 0x1b, 0x79, 0xa1, 0x88, 0xdb, 0xa5, 0x35, 0xaf, 0xe5, 0x9a, 0xd9, 0x47, 0x6f,
	0x22, 0xd4, 0xae, 0x53, 0x29, 0x47, 0x19, 0x27, 0x13, 0xdc, 0x3f, 0x50, 0x82, 0x77, 0x6f, 0x78,
	0x76, 0x97, 0xb1, 0x7b, 0xb5, 0xba, 0xc5, 0x8a, 0x61, 0xcd, 0x07, 0xa9, 0x7e, 0x2a, 0x12, 0xf6,
	0x32, 0x4f, 0x74, 0x8c, 0x5d, 0xd3, 0xf3, 0xe5, 0x60, 0xf0, 0x57, 0x2e, 0xf6, 0x9d, 0x6f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x9b, 0xe4, 0xeb, 0xbb, 0xbb, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*PostUserResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/Api/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*PostUserResponse, error) {
	out := new(PostUserResponse)
	err := c.cc.Invoke(ctx, "/Api/PostUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	PostUser(context.Context, *PostUserRequest) (*PostUserResponse, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedApiServer) PostUser(ctx context.Context, req *PostUserRequest) (*PostUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostUser not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Api/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PostUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PostUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Api/PostUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PostUser(ctx, req.(*PostUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Api_GetUser_Handler,
		},
		{
			MethodName: "PostUser",
			Handler:    _Api_PostUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
